const express = require("express");
const router = express.Router();
const authController = require("../controllers/auth.controller");
const userController = require("../controllers/user.controller");
const requireAuth = require("../middleware/auth.middleware");
router.post("/register", authController.registerUser);
router.post("/login", authController.loginUser);
router.post("/logout", requireAuth, authController.logoutUser);
router.get("/me", requireAuth, authController.getCurrentUser);
module.exports = router;
